services:
  go-server:
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mysql
    volumes:
      - ./html:/app/html
      - ./script:/app/script
      - ./css:/app/css
    networks:
      - ZooServer

  # MySQL Database
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ZooDaba
    volumes:
      - ./database/script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
    networks:
      - ZooServer

volumes:
  mysql-data:

networks:
  ZooServer: