services:
  app:
    container_name: Zoo-Website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    volumes:
      - ./css:/app/css
      - ./html:/app/html
      - ./script:/app/script
    environment:
      - DB_USER=root
      - DB_ADDR=mysql:3306
      - DB_PORT=3306
      - DB_PASSWORD=1234
      - DB_NAME=ZooDaba
      - DB_NET=tcp
      - JWT_SECRET=KEY
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - go-network

  mysql:
    container_name: go-mysql
    image: mysql:9.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    command: --bind-address=0.0.0.0 --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./database/script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
    networks:
      - go-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  dbdata:

networks:
  go-network:
    driver: bridge
